<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TabsContentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tabsContent = [
            1 => [
                'title' => 'Electronics',
                'content' => 'Discover the latest gadgets and tech innovations.',
                'items' => [
                    'Smartphone - Samsung Galaxy S23',
                    'Laptop - MacBook Pro 16"',
                    'Wireless Earbuds - Sony WF-1000XM5',
                    'Smartwatch - Apple Watch Series 9',
                    'Tablet - iPad Pro 12.9"',
                    'Gaming Console - PlayStation 5',
                    'Camera - Sony Alpha A7 III',
                    'Speaker - JBL Charge 5',
                    'Drone - DJI Mavic Air 2',
                    'Fitness Tracker - Fitbit Charge 5',
                    'External Hard Drive - Seagate 2TB',
                    'Monitor - Dell UltraSharp 27"',
                    'Keyboard - Keychron K2 Mechanical Keyboard',
                    'Mouse - Logitech MX Master 3',
                    'Router - Netgear Nighthawk AX12',
                ],
            ],
            2 => [
                'title' => 'Clothing',
                'content' => 'Explore the trendiest outfits and fashion accessories.',
                'items' => [
                    'Men’s Jacket - North Face Apex',
                    'Women’s Dress - Zara Evening Gown',
                    'Unisex Sneakers - Nike Air Max',
                    'Scarf - Gucci Silk Scarf',
                    'Watch - Fossil Chronograph',
                    'T-Shirt - Levi’s Graphic Tee',
                    'Jeans - Wrangler Slim Fit',
                    'Sportswear - Adidas Training Pants',
                    'Winter Coat - Canada Goose Expedition Parka',
                    'Shoes - Clarks Desert Boots',
                    'Hat - Stetson Fedora',
                    'Bag - Herschel Supply Co. Backpack',
                    'Belt - Tommy Hilfiger Leather Belt',
                    'Sunglasses - Ray-Ban Aviator',
                    'Gloves - North Face Etip Gloves',
                ],
            ],
            3 => [
                'title' => 'Books',
                'content' => 'Immerse yourself in captivating stories and insightful reads.',
                'items' => [
                    'Fiction - "The Midnight Library" by Matt Haig',
                    'Self-Help - "Atomic Habits" by James Clear',
                    'Biography - "Steve Jobs" by Walter Isaacson',
                    'Thriller - "The Silent Patient" by Alex Michaelides',
                    'Fantasy - "A Court of Thorns and Roses" by Sarah J. Maas',
                    'Classic - "To Kill a Mockingbird" by Harper Lee',
                    'Science - "Sapiens" by Yuval Noah Harari',
                    'Mystery - "Gone Girl" by Gillian Flynn',
                    'Romance - "Pride and Prejudice" by Jane Austen',
                    'Adventure - "The Hobbit" by J.R.R. Tolkien',
                    'Philosophy - "Meditations" by Marcus Aurelius',
                    'Young Adult - "The Hunger Games" by Suzanne Collins',
                    'Historical Fiction - "The Nightingale" by Kristin Hannah',
                    'Horror - "It" by Stephen King',
                    'Science Fiction - "Dune" by Frank Herbert',
                ],
            ],
            4 => [
                'title' => 'Movies',
                'content' => 'Get recommendations on the latest movies.',
                'items' => [
                    'The Martian - A survivor from Mars',
                    'Big Hero 6 - A tech geek lost his brother tries to take revenge on the killer',
                    'The Chosen - A famous series in the community opening eyes of many',
                    'Inception - A mind-bending thriller by Christopher Nolan',
                    'Interstellar - Exploring the mysteries of space and time',
                    'The Dark Knight - A masterpiece by Christopher Nolan',
                    'Avengers: Endgame - The culmination of Marvel’s saga',
                    'Parasite - A thrilling social commentary',
                    'Forrest Gump - Life lessons from Forrest',
                    'The Godfather - A cinematic classic',
                    'Gladiator - A story of vengeance and redemption',
                    'The Shawshank Redemption - Hope and perseverance',
                    'Titanic - A timeless love story',
                    'Spider-Man: No Way Home - An epic multiverse saga',
                    'Coco - A heartfelt animated journey into music and family',
                ],
            ],
            5 => [
                'title' => 'Travel',
                'content' => 'Plan your next adventure with these travel destinations.',
                'items' => [
                    'Paris, France - The city of lights and romance',
                    'Tokyo, Japan - A blend of tradition and modernity',
                    'Bali, Indonesia - Tropical paradise with serene beaches',
                    'New York, USA - The city that never sleeps',
                    'Cape Town, South Africa - Iconic landscapes and wildlife',
                    'Sydney, Australia - The famous Opera House and beaches',
                    'Rome, Italy - Explore ancient ruins and culture',
                    'Dubai, UAE - A hub of luxury and innovation',
                    'Kyoto, Japan - Traditional temples and cherry blossoms',
                    'Reykjavik, Iceland - Northern lights and glaciers',
                    'Santorini, Greece - Stunning sunsets and whitewashed homes',
                    'Hawaii, USA - Exotic islands and volcanoes',
                    'Rio de Janeiro, Brazil - Carnival and breathtaking views',
                    'London, UK - Historic landmarks and modern life',
                    'Machu Picchu, Peru - Ancient Incan ruins',
                ],
            ],
            6 => [
                'title' => 'Food',
                'content' => 'Delight your taste buds with these culinary picks.',
                'items' => [
                    'Pizza - Authentic Neapolitan Pizza',
                    'Sushi - Fresh Tuna Nigiri',
                    'Dessert - Belgian Chocolate Mousse',
                    'Burger - Wagyu Beef Cheeseburger',
                    'Pasta - Spaghetti Carbonara',
                    'Salad - Caesar Salad',
                    'Steak - Ribeye with Garlic Butter',
                    'Tacos - Mexican Street Tacos',
                    'Dessert - New York Cheesecake',
                    'Seafood - Grilled Lobster with Lemon Butter',
                    'Breakfast - French Toast with Maple Syrup',
                    'Soup - Tomato Basil Soup',
                    'Snack - Nachos with Salsa and Cheese',
                    'Drink - Freshly Brewed Cappuccino',
                    'Ice Cream - Artisan Gelato',
                ],
            ],
            7 => [
                'title' => 'Fitness',
                'content' => 'Gear up for a healthy lifestyle with these essentials.',
                'items' => [
                    'Dumbbells - Adjustable Weight Set',
                    'Yoga Mat - Non-Slip Eco-Friendly Mat',
                    'Resistance Bands - Multi-Level Set',
                    'Running Shoes - Adidas Ultraboost',
                    'Fitness Tracker - Fitbit Charge 5',
                    'Kettlebell - Cast Iron Weight',
                    'Treadmill - NordicTrack Commercial Series',
                    'Exercise Bike - Peloton Bike+',
                    'Jump Rope - CrossFit Speed Rope',
                    'Foam Roller - TriggerPoint Grid',
                    'Pull-Up Bar - Doorway Mounted',
                    'Protein Powder - Whey Isolate',
                    'Water Bottle - Stainless Steel Insulated',
                    'Workout Gloves - Harbinger Training Gloves',
                    'Stretching Strap - Yoga and Mobility Aid',
                ],
            ],
            8 => [
                'title' => 'Gaming',
                'content' => 'Level up your gaming experience with these top picks.',
                'items' => [
                    'Console - PlayStation 5',
                    'Game - "The Legend of Zelda: Breath of the Wild"',
                    'Accessory - Logitech G502 Gaming Mouse',
                    'Headset - Razer Kraken Ultimate',
                    'Chair - Secretlab Titan Evo 2023',
                    'Game - "Elden Ring"',
                    'Monitor - ASUS ROG Swift 27"',
                    'Keyboard - Corsair K95 RGB Platinum',
                    'Controller - Xbox Elite Series 2',
                    'VR Headset - Oculus Quest 2',
                    'Gaming Desk - Arozzi Arena',
                    'Mousepad - HyperX Fury S',
                    'Light - Philips Hue Play',
                    'Game - "Cyberpunk 2077"',
                    'Streaming Mic - Blue Yeti Nano',
                ],
            ],
        ];
    }
}
